# Generated by Django 3.0.6 on 2020-05-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=40)),
                ('pizza_type', models.CharField(blank=True, max_length=40, null=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('username', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now=True)),
                ('order_status', models.BooleanField(default=False)),
                ('pizza_toppings', models.ManyToManyField(blank=True, related_name='orders', to='orders.Toppings')),
                ('sub_additions', models.ManyToManyField(blank=True, related_name='orders', to='orders.Extras')),
            ],
        ),
    ]
